server:
  port: 8080
  servlet:
    context-path: /
  address: 0.0.0.0

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: elderly-platform
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5433}/elderly_platform
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.sendgrid.net
    port: 2525
    username: apikey
    password: ${SENDGRID_API_KEY:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:8640000}
  refresh:
    secret: ${JWT_REFRESH_SECRET:}
    expiration: ${JWT_REFRESH_EXPIRATION:864000000}
  algorithms: HmacSHA256

swagger:
  app:
    name: ElderlyCarePlatform
  add:
    security:
      name: ElderlyCarePlatformSecurity
  scheme: Bearer
  format: JWT
  dev:
    url: http://localhost:8080/
  pro:
#    url: https://elderlycareplatform.azurewebsites.net/
    url: http://157.245.155.77:8080/

application:
  default:
    current-page: 1
    page-size: 5
  service-package:
    allowed-duration-hours: 4,8  # Các giá trị duration hours được phép (phân cách bằng dấu phẩy)
  caregiver:
    max-hours-per-week: 48  # Số giờ tối đa caregiver có thể làm việc trong 1 tuần

ai:
  matching:
    service:
      url: http://ai_matching:8000

# Core PayOS credentials
payos:
  client-id: ${PAYOS_CLIENT_ID:}
  api-key: ${PAYOS_API_KEY:}
  checksum-key: ${PAYOS_CHECKSUM_KEY:}

  # Optional: Payout credentials (leave empty if not using payouts)
  payout-client-id: ${PAYOS_PAYOUT_CLIENT_ID:}
  payout-api-key: ${PAYOS_PAYOUT_API_KEY:}
  payout-checksum-key: ${PAYOS_PAYOUT_CHECKSUM_KEY:}

  # Logging level: DEBUG | INFO | NONE
  log-level: NONE

  # Callback URLs
  url-success: /success
  url-cancel: /cancel

# Firebase
firebase:
  # Firebase Admin SDK credentials (Unified - dùng chung cho FCM & Storage)
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH:keys/key_firebase.json}
  app:
    name: ${FIREBASE_APP_NAME:elderly-platform-app}
  
  # Firebase Storage
  bucket:
    name: swp391-f046d.appspot.com
  get:
    url: https://firebasestorage.googleapis.com/v0/b/swp391-f046d.appspot.com/o/%s?alt=media
    folder: exe201_project
